[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "hpc-marwan-wiki"
authors = [{name = "HPC MARWAN TEAM", email = "hpc@marwan.ma"}]
dynamic = ["1.1", "HPC-MARWAN DOCUMENTATION"]
